[[redirects]]
  from = "/youtube"
  to = "https://youtube.com/@windbridge"
  status = 301
  force = true

[[redirects]]
  from = "/instagram"
  to = "https://instagram.com/ahmad.rka"
  status = 301
  force = true

[[redirects]]
  from = "/project"
  to = "https://anu.netlify.app/"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
